// <auto-generated />
namespace MvcApplication3.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTimeStampDepartament : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTimeStampDepartament));
        
        string IMigrationMetadata.Id
        {
            get { return "201211051627284_AddTimeStampDepartament"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
